name: serverpod_chat_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_auth_client:
    path: ../../serverpod_auth/serverpod_auth_client
