name: serverpod_auth_server
description: Starting point for a Serverpod module.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod: # ^0.8.6
    path: ../../../packages/serverpod
  googleapis: ^3.0.0
  googleapis_auth: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
