name: serverpod_client
version: 0.0.1
description: A sample command-line application
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  serverpod_serialization:
    path: ../serverpod_serialization
  http: ^0.13.0

dev_dependencies:
#  unittest: any
