name: serverpod_client
version: 0.8.0
description: Base classes for communication with the server.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_serialization:
    path: ../serverpod_serialization
  http: ^0.13.0
