# TEMPLATE
PUBLISH_TO

name: serverpod_client
version: VERSION
description: Base classes for communication with the server.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_serialization: #^VERSION
    path: ../serverpod_serialization
  http: ^0.13.0
