name: serverpod
version: 0.0.1
description: The easiest server api you've ever used
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  args: ^1.5.1
  collection: ^1.14.11
  postgres:
    path: ../../../postgresql-dart
  yaml: ^2.1.15
  serverpod_serialization:
    path: ../serverpod_serialization
  resource: ^2.1.5

dev_dependencies:
  test: ^1.6.3
