name: serverpod
version: 0.0.1
description: The easiest server api you've ever used
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  args: ^2.0.0
  collection: ^1.15.0
  postgres: ^2.3.0
#  postgres_pool: ^2.1.0
  postgres_pool:
    path: ../../../postgres_pool
  yaml: ^3.1.0
  serverpod_shared:
    path: ../serverpod_shared
  serverpod_serialization:
    path: ../serverpod_serialization
  serverpod_service_client:
    path: ../serverpod_service_client

dev_dependencies:
  test: ^1.16.8
  serverpod_test_client:
    path: ../../tests/serverpod_test_client
