name: example_server
version: 0.0.1
description: A sample command-line application
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  serverpod:
    path: ../../packages/serverpod

dev_dependencies:
#  unittest: any
