# TEMPLATE
PUBLISH_TO

name: serverpod_shared
version: VERSION
description: Severpod code that is shared between serverpod and tooling.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  serverpod_client: #^VERSION
    path: ../serverpod_client

dev_dependencies:
  lints: ^1.0.1
