name: serverpod_cli
version: 0.0.1
description: A sample command-line application
dependencies:
  args:
  recase: ^2.0.1
  serverpod:
    path: ../serverpod

dev_dependencies:
#  unittest: any

executables:
  serverpod: serverpod_cli