shared:
  mySharedPassword: 'my password'
development:
  database: 'DATABASE_PASSWORD'
  serviceSecret: 'SERVICE_SECRET'
staging:
  database: 'DATABASE_PASSWORD'
  serviceSecret: 'SERVICE_SECRET'
production:
  database: 'DATABASE_PASSWORD'
  serviceSecret: 'SERVICE_SECRET'
  