name: serverpod_testbundle
description: A simple Serverpod bundle.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod:
    path: ../serverpod

dev_dependencies:
  pedantic: ^1.9.0
