type: server

generated_client_dart: ../serverpod_test_client/lib/src/protocol
generated_server_protocol: lib/src/generated
source_protocol: lib/src/protocol
source_endpoints: lib/src/endpoints

modules:
  serverpod_test_module:
    path: ../serverpod_test_module
    name: module