name: serverpod_service_client
version: 0.8.0
description: Generated client for the Severpod service protocol.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_client:
    path: ../serverpod_client
