name: serverpod_s3_server
description: Starting point for a Serverpod module.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod:
    path: ../../../packages/serverpod
  amazon_cognito_identity_dart_2: ^1.0.3
  built_value: ^8.1.3
  xml2json: ^5.3.1

dev_dependencies:
  pedantic: ^1.9.0
