name: serverpod_test_client
version: 0.0.1
description: A sample command-line application
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  serverpod:
    path: ../serverpod

dev_dependencies:
#  unittest: any