name: serverpod_shared
version: 0.8.0
description: Severpod code that is shared between serverpod and tooling.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  serverpod_client:
    path: ../serverpod_client
