# TEMPLATE
PUBLISH_TO

name: serverpod
version: VERSION
description: Next generation app and web server.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.11.0
  args: ^2.0.0
  collection: ^1.15.0
  crypto: ^3.0.1
  postgres: ^2.3.0
  serverpod_postgres_pool: ^2.1.1
  yaml: ^3.1.0
  serverpod_shared: #^VERSION
    path: ../serverpod_shared
  serverpod_serialization: #^VERSION
    path: ../serverpod_serialization
  serverpod_service_client: #^VERSION
    path: ../serverpod_service_client
  serverpod_client: #^VERSION
    path: ../serverpod_client

dev_dependencies:
  test: ^1.16.8
  serverpod_test_client:
    path: ../../tests/serverpod_test_client
  serverpod_test_module_client: #^VERSION
    path: ../../tests/serverpod_test_module/serverpod_test_module_client
