name: serverpod_test_server
version: 0.0.1
description: A sample command-line application
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  serverpod:
    path: ../serverpod
  serverpod_relic:
    path: ../serverpod_relic
  serverpod_test_module:
    path: ../serverpod_test_module

dev_dependencies:
#  unittest: any
