name: serverpod_auth_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  lints: ^1.0.1
  serverpod_client:
    path: ../../../packages/serverpod_client
