name: serverpod_relic
version: VERSION
description: Web server for Serverpod (still experimental, but working).

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mustache_template: ^2.0.0
  yaml: ^3.1.0
  serverpod: #^VERSION
    path: ../serverpod
