# TEMPLATE
PUBLISH_TO

name: serverpod_relic
version: VERSION
description: Web server for Serverpod (still experimental, but working).
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mustache_template: ^2.0.0
  path: ^1.8.0
  yaml: ^3.1.0
  serverpod: #^VERSION
    path: ../serverpod

dev_dependencies:
  lints: ^1.0.1
