# TEMPLATE
PUBLISH_TO

name: serverpod_service_client
version: VERSION
description: Generated client for the Severpod service protocol.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_client: #^VERSION
    path: ../serverpod_client

dev_dependencies:
  lints: ^1.0.1
