# TEMPLATE

name: serverpod_service_client
version: VERSION
description: Generated client for the Severpod service protocol.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_client: #^VERSION
    path: ../serverpod_client
