name: Serverpod CI

on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master
jobs:
  dart_format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.14.2

      # - name: Install dependencies
      #   run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #  run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #  run: dart test
  dart_analyze:
    name: Analyze ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - packages/serverpod
          - packages/serverpod_client
          - packages/serverpod_relic
          - packages/serverpod_serialization
          - packages/serverpod_service_client
          - packages/serverpod_shared
          - tests/serverpod_test_server
          - tests/serverpod_test_client
          - tests/serverpod_test_module/serverpod_test_module_server
          - tests/serverpod_test_module/serverpod_test_module_client
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.14.2
      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ matrix.package }}
      - name: Analyze
        run: dart analyze
        working-directory: ${{ matrix.package }}

  single_server_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run single server tests
        run: util/run_tests_single_server
